version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Build UE5 Project
          command: |
            # 设置环境变量，确保使用正确的编译器版本
            "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
            # 构建 Unreal Engine 项目
            # "C:\UnrealEngine\Engine\Build\BatchFiles\Build.bat" MyProject Win64 Development -WaitMutex
            D:/WP_YXK/UE/UE_5.3/Engine/Build/BatchFiles/RunUAT.bat BuildGraph -Target=Windows Cook -Script=E:/WorkPlace/WP_YXK/ue5_build_graph_demo/Tools/BuildGraph.xml -Export=E:/WorkPlace/WP_YXK/ue5_build_graph_demo/Tools/ExportedGraph.json
            E:/WorkPlace/WP_YXK/ue5_build_graph_demo/Tools/buildgraph-to-circleci/buildgraph-to-circleci.py --json-graph E:/WorkPlace/WP_YXK/ue5_build_graph_demo/Tools/ExportedGraph.json > E:/WorkPlace/WP_YXK/ue5_build_graph_demo/Tools/generated_config.yml